/** Quick-chat canned messages. The server accepts only ids on this list. */

export interface CannedMessage {
  id: string
  text: string
}

export const CANNED_MESSAGES: readonly CannedMessage[] = [
  { id: 'hello', text: '哈囉，請多指教！' },
  { id: 'hurry', text: '快下啦～' },
  { id: 'thinking-long', text: '想這麼久喔？' },
  { id: 'nice-move', text: '好棋！' },
  { id: 'oops', text: '哎呀，失誤了…' },
  { id: 'doomed', text: '你完蛋了 😏' },
  { id: 'wait', text: '等等，讓我想一下' },
  { id: 'thanks', text: '承讓承讓～' },
  { id: 'trap', text: '這步是陷阱吧？' },
  { id: 'lucky-flip', text: '翻到好棋，羨慕！' },
  { id: 'lag', text: '網路卡了嗎？' },
  { id: 'rematch', text: '再來一局啦！' },
  { id: 'gg', text: 'GG，打得不錯 🫡' },
  { id: 'laugh', text: '哈哈哈哈笑死 😂' },
  { id: 'sweat', text: '冷汗直流 💦' },
  { id: 'confident', text: '穩了穩了，這把穩了 😎' },
  { id: 'panic', text: '慘了慘了 😱' },
  { id: 'come-on', text: '來啊，誰怕誰 🔥' },
  { id: 'no-way', text: '不會吧，這樣也行？🙄' },
  { id: 'turtle', text: '你是慢動作重播嗎 🐢' },
  { id: 'hand-slip', text: '剛剛是手滑，不算！' },
  { id: 'next-time', text: '下次我一定贏回來 💪' },
  { id: 'kneel', text: '太強了，膝蓋給你 🙇' },
  { id: 'pure-luck', text: '純粹運氣好而已 🎲' },
  { id: 'scared', text: '你在怕什麼 😏' },
  { id: 'sleepy', text: '想那麼久，睡著了嗎 😴' },
  { id: 'trump-card', text: '看我的大招 ✨' },
  { id: 'sorry', text: '抱歉抱歉，手誤手誤 🙏' },
  { id: 'well-played', text: '打得漂亮 👏' },
  { id: 'crying', text: '我要哭了啦 😭' },
  { id: 'messy', text: '你這棋下得跟我房間一樣亂 🫠' },
  { id: 'brain-melt', text: '好燒腦，CPU 要燒了 🤯' },
  { id: 'mercy', text: '饒了我吧 🥺' },
  { id: 'popcorn', text: '好戲在後頭，先吃爆米花 🍿' },
  { id: 'flip-god', text: '又是你翻？你是牌神喔 🃏' },
  { id: 'all-in', text: '一步定生死，衝了 ⚔️' },
  { id: 'bad-luck', text: '乾～太倒楣了吧！' },
  { id: 'gan-gan-gan', text: '乾乾乾乾乾～' },
  { id: 'are-you-serious', text: '你認真？' },
  { id: 'so-close', text: '好險好險，差一點 💨' },
  { id: 'unbelievable', text: '天啊，我不敢相信 😳' },
  { id: 'bluff', text: '這步是虛張聲勢喔 😜' },
  { id: 'no-peeking', text: '別偷看我的棋啦 👀' },
  { id: 'sweaty', text: '手都在抖了，好緊張 😬' },
  { id: 'hide-only', text: '只敢蓋牌，不敢翻？🐔' },
  { id: 'gamble', text: '賭一把，翻！🃏' },
  { id: 'addictive', text: '這遊戲也太上頭了吧 🔁' },
  { id: 'one-more', text: '最後一局，說好的 🤞' },
  { id: 'tsk', text: '嘖，這手虧大了…' },
  { id: 'comeback', text: '逆轉秀要開始了 🎬' },
  { id: 'give-up', text: '投降認輸，別追了 🏳️' },
  { id: 'shh', text: '噓，別吵，我在算棋 🤫' },
  { id: 'teach-me', text: '拜託教我一下 🙏' },
  { id: 'who-are-you', text: '你到底是何方神聖 😨' },
  { id: 'newbie', text: '我是新手，手下留情 🐣' },
  { id: 'veteran', text: '薑還是老的辣 🧂' },
  { id: 'bathroom', text: '等我一下，去個洗手間 🚻' },
  { id: 'phone', text: '手機一直震，分心了 📱' },
  { id: 'snack-time', text: '一手拿零食一手下棋 🍟' },
  { id: 'clock-race', text: '秒針在追殺我 ⏱️' },
  { id: 'pause', text: '暫停暫停，讓我緩一下 🖐️' },
  { id: 'nice-flip', text: '這翻得漂亮 ✨' },
  { id: 'mine', text: '翻到炸彈了，完了 💣' },
  { id: 'cannon', text: '炮來了，小心 🧨' },
  { id: 'horse', text: '馬上將軍 🐴' },
  { id: 'check', text: '將軍！嚇到了吧 😈' },
  { id: 'protect', text: '保護主將要緊 🛡️' },
  { id: 'ambush', text: '陷阱發動，不好意思 😇' },
  { id: 'no-regret', text: '落子無悔喔 😌' },
  { id: 'take-back', text: '讓我悔棋一下嘛 🥹' },
  { id: 'mirror', text: '你我棋風根本雙胞胎 🪞' },
  { id: 'mind-reader', text: '你裝讀心術喔 🔮' },
  { id: 'tilt', text: '心態要炸裂了 😤' },
  { id: 'breathe', text: '深呼吸，穩住 ⛰️' },
  { id: 'tea', text: '先喝口茶再戰 🍵' },
  { id: 'time-flies', text: '怎麼一下就過了十分鐘 ⏰' },
]

export function cannedText(id: string): string | null {
  return CANNED_MESSAGES.find((m) => m.id === id)?.text ?? null
}
